### ISSUE TITLE
Issue with solana-swap python API #1

### ISSUE THREAD

**Issue by neochine** [YZYLAB/solana-swap-python#1]
Functions are marked async yet they use requests library which is sync and blocking by nature (use aiohttp or similar libraries instead). Also it uses from `solana.rpc.api import Client` instead of `from solana.rpc.async_api import *`
This needs to be fixed. Perhaps a separate classes for Sync & Async would be ideal.

**Comment by neochine** [comment]
Not that good at async stuff otherwise I would have opened PR possibly

**Comment by YZYLAB** [comment]
Will have a look at this. Thank you.
