### ISSUE TITLE
Any advice on what would be best way to fix it?

### ISSUE THREAD

**Issue by neochine** [YZYLAB/solana-swap-python#3]
```   
    response = self.connection.send_raw_transaction(bytes(txn))\    n  File "/usr/local/lib/python3.9/dist-packages/solana/rpc/api.py", line 974, in send_raw_transaction
    resp = self._provider.make_request(body, SendTransactionResp)
  File "/usr/local/l    ib/python3.9/dist-packages/solana/exceptions.py", line 43, in argument_decorator
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/solana/rpc/providers/http.p    y", line 49, in make_request
    return _parse_raw(raw, parser=parser)
  File "/usr/local/lib/python3.9/dist-packages/solana/rpc/providers/core.py", line 97, in _parse_raw
    raise RPCEx    ception(parsed)
solana.rpc.core.RPCException: SendTransactionPreflightFailureMessage { message: "Transaction simulation failed: Blockhash not found", data: RpcSimulateTransactionResult(RpcS    imulateTransactionResult { err: Some(BlockhashNotFound), logs: Some([]), accounts: None, units_consumed: Some(0), return_data: None, inner_instructions: None }) }
```
This error seems to be in perform_swap function. I see `https://solana.stackexchange.com/questions/6093/blockhash-not-found-when-sending-transaction` this where `const { blockhash } = await connection.getLatestBlockhash("confirmed")` was the fix however ` Hi. For me, it worked the opposite way. I was using "confirmed". I changed to "finalized" and it worked. So I suggest testing both if you are getting "Blockhash not found" ` Finalized also works instead of confirm. I am already retrying swap function four times yet it fails
![image](https://github.com/YZYLAB/solana-swap-python/assets/150173528/b1faaa08-ba49-4da6-a24d-b799c6f3a85f)

**Comment by neochine** [comment]
![2024_05_12_0ro_Kleki](https://github.com/YZYLAB/solana-swap-python/assets/150173528/7b3bb270-6345-43bd-a420-52d3b8a83dba)

**Comment by YZYLAB** [comment]
Maybe change `self.connection = Client(rpc)` to `self.connection = Client(rpc, commitment="confirmed")`

**Comment by neochine** [comment]
Alright. I am setting that and also setting number of retries to 8
